/**
 * Events generated by the Parser class
 */
public class ParserEvent {

    private ParserTypeEventEnum typeEvent;
    private Octave octave;
    private Note note;
    private Duration duration;
    private Bpm bpm;
    private Volume volume;
    private Instrument instrument;


    public ParserEvent(Bpm inputBpm, Instrument inputInstrument, Volume inputVolume, Octave inputOctave, ParserTypeEventEnum inputEventType){
        final int FILLER_VALUE = 1;

        this.typeEvent = inputEventType;
        this.octave = new Octave(inputOctave);
        this.note = new Note(FILLER_VALUE);
        this.duration = new Duration(); //The only duration used is 1
        this.bpm = new Bpm(inputBpm);
        this.volume = new Volume(inputVolume);
        this.instrument = new Instrument(inputInstrument);
    }

    public ParserEvent(ParserEvent copy){
        this.typeEvent = copy.typeEvent;
        this.octave = new Octave(copy.octave);
        this.note = new Note(copy.note);
        this.duration = new Duration();
        this.bpm = new Bpm(copy.bpm);
        this.volume = new Volume(copy.volume);
        this.instrument = new Instrument(copy.instrument);
    }

//FIX: Primitive Obsession
    public void increaseBpmEvent(){
        bpm.increaseBpm();
        //solve this (maybe)
        this.setTypeEvent(ParserTypeEventEnum.NEW_BPM);
    }

    public void decreaseBpmEvent(){
        this.bpm.decreaseBpm();
        this.setTypeEvent(ParserTypeEventEnum.NEW_BPM);
    }

    public void increaseOctaveEvent(){
        this.octave.increaseOctave();
        this.setTypeEvent(ParserTypeEventEnum.GENERIC);
    }

    public void decreaseOctaveEvent(){
        octave.decreaseOctave();
        this.setTypeEvent(ParserTypeEventEnum.GENERIC);
    }
    public void doubleVolumeEvent(){
        this.volume.doubleVolume();
        this.setTypeEvent(ParserTypeEventEnum.GENERIC);
    }

    public void addValueToInstrumentEvent(int value){
        instrument.addValueToInstrument(value);
        this.setTypeEvent(ParserTypeEventEnum.NEW_INSTRUMENT);
    }

    public void updateInstrument(int value){
        instrument.setValue(value);
        this.setTypeEvent(ParserTypeEventEnum.NEW_INSTRUMENT);
    }


    public void setTypeEvent(ParserTypeEventEnum type){
        this.typeEvent = type;
    }

    public void setNoteEvent(int noteInput) {
        this.note.setValue(noteInput);
    }
    public void setFlatNoteEvent(Note noteInput){
        this.note.setFlatNote(noteInput);
    }


    public void setBpm (Bpm inputBpm) {
        this.bpm.setValue(inputBpm.getValue());
    }

    //should be indexed into an ENUM for types of events (is currently in MusicEventClass)
    public ParserTypeEventEnum getTypeEvent(){ return this.typeEvent; }

    public Octave getOctave(){
        return this.octave;
    }

    public int getAbsoluteNote () {
        return (this.octave.getNoteOffset()) + this.note.getValue();
    }

    public Duration getDuration(){ return this.duration; }

    public Bpm getBpm(){ return this.bpm; }

    public Volume getVolume() { return this.volume; }

    public Instrument getInstrument(){ return this.instrument; }
}
